// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using uchebkaPZ1tt.Models;

#nullable disable

namespace uchebkaPZ1tt.Migrations
{
    [DbContext(typeof(Ispr2524LinkovNIUchebkaContext))]
    partial class Ispr2524LinkovNIUchebkaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");

            modelBuilder.Entity("uchebkaPZ1tt.Models.InputDataComment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("commentID");

                    b.Property<int?>("MasterId")
                        .HasColumnType("int")
                        .HasColumnName("masterID");

                    b.Property<string>("Message")
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<int?>("RequestId")
                        .HasColumnType("int")
                        .HasColumnName("requestID");

                    b.HasKey("CommentId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "RequestId" }, "FK_MIDD_idx");

                    b.HasIndex(new[] { "MasterId" }, "FK_MID_idx");

                    b.ToTable("inputDataComments", (string)null);
                });

            modelBuilder.Entity("uchebkaPZ1tt.Models.InputDataRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .HasColumnType("int")
                        .HasColumnName("requestID");

                    b.Property<int>("ClientId")
                        .HasColumnType("int")
                        .HasColumnName("clientID");

                    b.Property<string>("CompletionDate")
                        .HasColumnType("text")
                        .HasColumnName("completionDate");

                    b.Property<string>("ComputerTechModel")
                        .HasColumnType("text")
                        .HasColumnName("computerTechModel");

                    b.Property<string>("ComputerTechType")
                        .HasColumnType("text")
                        .HasColumnName("computerTechType");

                    b.Property<int?>("MasterId")
                        .HasColumnType("int")
                        .HasColumnName("masterID");

                    b.Property<string>("ProblemDescryption")
                        .HasColumnType("text")
                        .HasColumnName("problemDescryption");

                    b.Property<string>("RepairParts")
                        .HasColumnType("text")
                        .HasColumnName("repairParts");

                    b.Property<string>("RequestStatus")
                        .HasColumnType("text")
                        .HasColumnName("requestStatus");

                    b.Property<string>("StartDate")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("startDate");

                    b.HasKey("RequestId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ClientId" }, "FK_KID_idx");

                    b.HasIndex(new[] { "MasterId" }, "FK_MIDD_idx")
                        .HasDatabaseName("FK_MIDD_idx1");

                    b.ToTable("inputDataRequests", (string)null);
                });

            modelBuilder.Entity("uchebkaPZ1tt.Models.InputDataUser", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("userID");

                    b.Property<string>("Fio")
                        .HasColumnType("text")
                        .HasColumnName("fio");

                    b.Property<string>("Login")
                        .HasColumnType("text")
                        .HasColumnName("login");

                    b.Property<string>("Password")
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<long?>("Phone")
                        .HasColumnType("bigint")
                        .HasColumnName("phone");

                    b.Property<string>("Type")
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("UserId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Phone" }, "phone_UNIQUE")
                        .IsUnique();

                    b.ToTable("inputDataUsers", (string)null);
                });

            modelBuilder.Entity("uchebkaPZ1tt.Models.InputDataComment", b =>
                {
                    b.HasOne("uchebkaPZ1tt.Models.InputDataUser", "Master")
                        .WithMany("InputDataComments")
                        .HasForeignKey("MasterId")
                        .HasConstraintName("FK_MID");

                    b.HasOne("uchebkaPZ1tt.Models.InputDataRequest", "Request")
                        .WithMany("InputDataComments")
                        .HasForeignKey("RequestId")
                        .HasConstraintName("FK_RID");

                    b.Navigation("Master");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("uchebkaPZ1tt.Models.InputDataRequest", b =>
                {
                    b.HasOne("uchebkaPZ1tt.Models.InputDataUser", "Client")
                        .WithMany("InputDataRequestClients")
                        .HasForeignKey("ClientId")
                        .IsRequired()
                        .HasConstraintName("FK_KID");

                    b.HasOne("uchebkaPZ1tt.Models.InputDataUser", "Master")
                        .WithMany("InputDataRequestMasters")
                        .HasForeignKey("MasterId")
                        .HasConstraintName("FK_MIDD");

                    b.Navigation("Client");

                    b.Navigation("Master");
                });

            modelBuilder.Entity("uchebkaPZ1tt.Models.InputDataRequest", b =>
                {
                    b.Navigation("InputDataComments");
                });

            modelBuilder.Entity("uchebkaPZ1tt.Models.InputDataUser", b =>
                {
                    b.Navigation("InputDataComments");

                    b.Navigation("InputDataRequestClients");

                    b.Navigation("InputDataRequestMasters");
                });
#pragma warning restore 612, 618
        }
    }
}
